name: Deploy Application
on: push
jobs:
  lint_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run lint script
        run: npm lint
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run test script
        run: npm test
  deploy_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        run: npm build